### ISSUE TITLE
Research Paper Link

### ISSUE THREAD

**Issue by vvenkatesh-ML** [shivi98g/Fair-k-means-Clustering-via-Algorithmic-Fairness#1]
Hi There, this codebase is very helpful for some research I am doing as well. 
Would it be possible to link the research paper as well? I was unable to find the paper. 
Thanks!

**Comment by shivi98g** [comment]
https://arxiv.org/abs/2109.00708

**Comment by vvenkatesh-ML** [comment]
Thanks so much!
